apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
spec:
  # revisionHistoryLimit: 5
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
      # namespace: backend
    spec:
      containers:
      - name: simple-web
        image: pujosn/simple-web:1.1.0
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
spec:
  selector:
    app: simple-web
  ports:
  - port: 8080
    targetPort: 80
