apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  # revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
      # namespace: backend
    spec:
      containers:
      - name: simple-app
        image: pujosn/web-app:1.1.2
        imagePullPolicy: Always
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: simple-app-8080-service
spec:
  selector:
    app: simple-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
